### PR TITLE
Remove leftovers

### PR DESCRIPTION
**Pull request by Croydon**
These files are not needed anymore.

### CODE REVIEW

**Comment by Fohlen** [comment]
I wouldn't remove the `Jenkinsfile` because who knows if we will use Jenkins in the future again?

**Comment by Croydon** [comment]
Then we can readd it again

**Comment by Croydon** [comment]
Who knows if it works anyway and will keep working with changes we merge when nobody is using the Jenkinsfile.

**Comment by Fohlen** [comment]
Ok

**Pull request merged**
