### PR TITLE
fix(deploy/appveyor): debug output + multiline ps if statement

### PR DESCRIPTION
**Pull request by a-teammate**
the former powershell line is working locally and fails in the CI just if the second statement is true. change to workaround that

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2ec57e84e1b5e8ef014e65b0bcd0565b8875fe6a
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/inexorgame/inexor-core/wiki/Git-FAQ#how-should-i-format-my-git-commit-message

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1385338dac82da7c67a083c4291a98b5dee8800f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/inexorgame/inexor-core/wiki/Git-FAQ#how-should-i-format-my-git-commit-message

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1385338dac82da7c67a083c4291a98b5dee8800f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/inexorgame/inexor-core/wiki/Git-FAQ#how-should-i-format-my-git-commit-message

---
This message was auto-generated by https://gitcop.com

**Comment by a-teammate** [comment]
this PR should be ready.

**Comment by a-teammate** [comment]
Guys a review!

**Comment by Croydon** [comment]
Hold your door, some people aren't around 24/7 :)

Do we save the media repositories now within media/ ?
If yes, I would like to keep the readme file.

**Comment by a-teammate** [comment]
No we don't, in fact they are like everywhere else (see #152 or Media.js)

**Comment by Croydon** [comment]
I guess it is a bit odd when we save our media core to the same location like any other custom media repo, but that is another discussion.

**Pull request merged**
